apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: squidgame
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
      annotations:
        linkerd.io/inject: enabled
    spec:
      hostname: grpc-pod-host
      containers:
        - name: grpc-client-api
          image: alexixva/grpc_client_api
          env:
          - name: HOST
            value: grpc-pod-host
          ports:
            - containerPort: 2000
          resources: {}
        - name: grpc-server
          image: alexixva/grpc_server
          ports:
            - containerPort: 50051
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
  namespace: squidgame
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: myapp
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbit
      annotations:
        linkerd.io/inject: enabled
    spec:
      hostname: grpc-pod-host
      containers:
        - name: grpc-client-api
          image: alexixva/grpc_client_api
          env:
          - name: HOST
            value: grpc-pod-host
          ports:
            - containerPort: 2000
          resources: {}
        - name: grpc-server
          image: alexixva/grpc_server
          ports:
            - containerPort: 50051
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
  namespace: squidgame
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: rabbit
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pubsub
  name: pubsub
  namespace: squidgame
spec:
  replicas: 3 # Segun replicas que pide el enunciado
  selector:
    matchLabels:
      app: pubsub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pubsub
      annotations:
        linkerd.io/inject: enabled
    spec:
      hostname: grpc-pod-host
      containers:
        - name: grpc-client-api
          image: alexixva/grpc_client_api
          env:
          - name: HOST
            value: grpc-pod-host
          ports:
            - containerPort: 2000
          resources: {}
        - name: grpc-server
          image: alexixva/grpc_server
          ports:
            - containerPort: 50051
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pubsub
  name: pubsub
  namespace: squidgame
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: pubsub
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: minimal-ingress 
  annotations: 
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
  namespace: squidgame
spec: 
  rules: 
  - host: 34.68.185.157.nip.io
    http: #Se agregan los servicios que tendra este host
      paths: 
      - path: / #/myapp
        pathType: Prefix 
        backend: 
          service: 
            name: myapp 
            port: 
              number: 2000 
        path: / #/rabbit
        pathType: Prefix 
        backend: 
          service: 
            name: rabbit 
            port: 
              number: 2000
        path: / #/pubsub
        pathType: Prefix 
        backend: 
          service: 
            name: pubsub 
            port: 
              number: 2000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-injector
  namespace: squidgame
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 5000;
            location / {
                return 500;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-injector
  namespace: squidgame
  labels:
    app: error-injector
spec:
  selector:
    matchLabels:
      app: error-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: error-injector
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: error-injector
---
apiVersion: v1
kind: Service
metadata:
  name: error-injector
  namespace: squidgame
spec:
  ports:
  - name: service
    port: 5000
  selector:
    app: error-injector
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: squidgame
spec:
  service: myapp
  backends:
  - service: myapp
    weight: 300m
  - service: rabbit
    weight: 300m
  - service: pubsub
    weight: 300m
  - service: error-injector
    weight: 100m
