apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: squidgame
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: alexixva/python-2
        name: python-2
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
  namespace: squidgame
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kafka
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbit
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: alexixva/python-3
        name: python-3
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbit
  name: rabbit
  namespace: squidgame
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rabbit
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pubsub
  name: pubsub
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pubsub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pubsub
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: alexixva/python-flask-distroless
        name: python-flask-distroless
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pubsub
  name: pubsub
  namespace: squidgame
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pubsub
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: minimal-ingress 
  annotations: 
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: / 
    nginx.ingress.kubernetes.io/service-upstream: "true"
  namespace: squidgame
spec: 
  rules: 
  - host: 34.134.109.145.nip.io
    http: 
      paths: 
      - path: /kafka
        pathType: Prefix 
        backend: 
          service: 
            name: kafka 
            port: 
              number: 5000 
  - host: 34.134.109.145.nip.io
    http: 
      paths: 
      - path: /rabbit
        pathType: Prefix 
        backend: 
          service: 
            name: rabbit 
            port: 
              number: 5000
  - host: 34.134.109.145.nip.io
    http: 
      paths: 
      - path: /pubsub
        pathType: Prefix 
        backend: 
          service: 
            name: pubsub 
            port: 
              number: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-injector
  namespace: squidgame
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 5000;
            location / {
                return 500;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-injector
  namespace: squidgame
  labels:
    app: error-injector
spec:
  selector:
    matchLabels:
      app: error-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: error-injector
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: error-injector
---
apiVersion: v1
kind: Service
metadata:
  name: error-injector
  namespace: squidgame
spec:
  ports:
  - name: service
    port: 5000
  selector:
    app: error-injector
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: squidgame
spec:
  #service: pubsub
  backends:
  - service: kafka
    weight: 300m
  - service: rabbit
    weight: 300m
  - service: pubsub
    weight: 300m
  - service: error-injector
    weight: 100m
