version: "3.3"
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    env_file:
    - kafka/kv.env
    depends_on:
    - zookeeper
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'

  consumer:
      build: ./Consumer
      restart: on-failure
      depends_on: 
        - kafka
    

  producer:
      build: ./Producer
      restart: on-failure
      ports:
          - "80:8080"
      depends_on: 
          - kafka
